name: Deploy Hugo Website to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  cv_change_detection:
    runs-on: ubuntu-latest
    outputs:
      cv: ${{ steps.filter.outputs.cv }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Detect changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        base: gh-pages
        filters: |
          cv:
            - 'assets/cv/**'    # any of the files in cv directory

  build_cv:
    name: Build CV
    runs-on: ubuntu-latest
    needs: cv_change_detection

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # - name: Compile CV
      #   uses: xu-cheng/latex-action@v3
      #   if: ${{ needs.cv_change_detection.outputs.cv == 'true' }}
      #   with:
      #     working_directory: ${{ github.workspace }}/assets/cv
      #     root_file: cv.tex
      #     extra_fonts: ./fonts/*
      #     latexmk_use_xelatex: true
  
      - name: Copy CV to static
        run: |
          echo ${{ github.workspace }} \ 
          ls ${{ github.workspace }} 
