name: Deploy Hugo Website to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  cv_change_detection:
    name: Detect changes in CV
    runs-on: ubuntu-latest
    outputs:
      cv: ${{ steps.filter.outputs.cv }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Detect changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        base: cv-snapshot   # compare against cv-snapshot branch
        filters: |
          cv:     # Any of the tex files in the cv directory
            - './assets/cv/cv.tex'    
            - './assets/cv/cv_data/*.tex'
    - run: | 
        echo "CV changed: ${{ steps.filter.outputs.cv }}"

  build_cv:
    name: Build CV
    runs-on: ubuntu-latest
    needs: cv_change_detection
    if: ${{ needs.cv_change_detection.outputs.cv == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./assets/cv
          root_file: cv.tex
          extra_fonts: ./fonts/*
          latexmk_use_lualatex: true
  
      - name: Copy CV to static
        run: |
          mkdir -p ${{ github.workspace }}/static/cv
          cp ${{ github.workspace }}/assets/cv/cv.pdf ${{ github.workspace }}/static/cv/cv.pdf

      - name: Commit and push changes in CV to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update cv and move to static/cv"
          branch: main

      - name: Push changes from main to cv-snapshot
        run: |
          git push --force origin main:cv-snapshot

  build_website:
    runs-on: ubuntu-latest
    needs: [cv_change_detection, build_cv]
    if: always() && (needs.build_cv.result == 'success' || needs.build_cv.result == 'skipped')
    name: Build and Deploy Website
    env:
      HUGO_VERSION: 0.140.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.140.2
          extended: true

      # - name: Setup Pages
      #   id: pages
      #   uses: actions/configure-pages@v5
      - name: Install Dart Sass
        run: sudo snap install dart-sass
        
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          export GOOGLE_ANALYTICS_ID="${{ secrets.GOOGLE_ANALYTICS_ID }}"
          hugo \
            --gc \
            --ignoreCache \
            --minify \
            --destination docs

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages    # Deploy the docs directory to gh-pages branch
          force_orphan: true